ALTER TABLE home_sections
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE admin_messages
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE garden_contents
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE service_tickets
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE search_operations
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE recommend_slots
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE message_templates
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sensitive_words
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE question_banks
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE practice_papers
  ADD COLUMN created_at TIMESTAMP NULL,
  ADD COLUMN updated_at TIMESTAMP NULL,
  ADD COLUMN created_by VARCHAR(64) NULL,
  ADD COLUMN updated_by VARCHAR(64) NULL,
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
