class RouterData {
  //   public getRouterData() {
  //     return [
  //       {
  //         path: '/',
  //         name: 'Home',
  //         component: () => import(/* webpackChunkName: "home" */ '@/views/Home.vue'),
  //         meta: {
  //           title: '首页',
  //           icon: 'home',
  //         },
  //       },
  //       {
  //         path: '/about',
  //         name: 'About',
  //         component: () => import(/* webpackChunkName: "about" */ '@/views/About.vue'),
  //         meta: {
  //           title: '关于',
  //           icon: 'about',
  //         },
  //       },
  //     ];
  //   }
  public getRouterData() {
    const data: { [key: string]: any } = {
      initiateApplication: {
        module: 'initiateApplication',
        name: '发起申请',
        config: {
          path: '/initiateApplication',
          name: 'initiateApplication',
          fullPath: '/initiateApplication',
          title: '发起申请',
          icon: 'initiateApplication',
          activeIcon: 'initiateApplicationShine',
          component: import(/* webpackChunkName: "initiateApplication" */ '@/pages/initiateApplication/initiateApplication.vue'),
          children: [],
          default: '/initiateApplication',
          meta: { keepAlive: true, title: '发起申请' },
          projects: ['FK'],
          order: 1,
          parentId: 0,
          permissionId: 1,
          showTab: true,
        },
      },
      paymentApplication: {
        module: 'paymentApplication',
        name: '付款申请',
        config: {
          path: '/paymentApplication',
          name: 'paymentApplication',
          fullPath: '/paymentApplication',
          title: '付款申请',
          icon: 'paymentApplication',
          activeIcon: 'paymentApplicationShine',
          component: import(/* webpackChunkName: "paymentApplication" */ '@/pages/paymentApplication/paymentApplication.vue'),
          children: [],
          default: '/paymentApplication',
          meta: { keepAlive: true, title: '付款申请' },
          projects: ['FK'],
          order: 2,
          parentId: 0,
          permissionId: 2,
        },
      },
      loanManagement: {
        module: 'loanManagement',
        name: '借款管理',
        config: {
          path: '/loanManagement',
          name: 'loanManagement',
          fullPath: '/loanManagement',
          title: '贷款管理',
          icon: 'loanManagement',
          activeIcon: 'loanManagementShine',
          component: import(/* webpackChunkName: "loanManagement" */ '@/pages/loanManagement/loanManagement.vue'),
          children: [],
          default: '/loanManagement',
          meta: { keepAlive: true, title: '贷款管理' },
          projects: ['FK'],
          order: 3,
          parentId: 0,
          permissionId: 3,
        },
      },
      reimburseManagement: {
        module: 'reimburseManagement',
        name: '报销管理',
        config: {
          path: '/reimburseManagement',
          name: 'reimburseManagement',
          fullPath: '/reimburseManagement',
          title: '报销管理',
          icon: 'reimburseManagement',
          activeIcon: 'reimburseManagementShine',
          component: import(/* webpackChunkName: "reimburseManagement" */ '@/pages/reimburseManagement/reimburseManagement.vue'),
          children: [],
          default: '/reimburseManagement',
          meta: { keepAlive: true, title: '报销管理' },
          projects: ['FK'],
          order: 4,
          parentId: 0,
          permissionId: 4,
        },
      },
      pendingInvoiceIssuance: {
        module: 'pendingInvoiceIssuance',
        name: '待开发票',
        config: {
          path: '/pendingInvoiceIssuance',
          name: 'pendingInvoiceIssuance',
          fullPath: '/pendingInvoiceIssuance',
          title: '待开发票',
          icon: 'pendingInvoiceIssuance',
          activeIcon: 'pendingInvoiceIssuanceShine',
          component: import(/* webpackChunkName: "pendingInvoiceIssuance" */ '@/pages/pendingInvoiceIssuance/pendingInvoiceIssuance.vue'),
          children: [],
          default: '/pendingInvoiceIssuance',
          meta: { keepAlive: true, title: '待开发票' },
          projects: ['FK'],
          order: 5,
          parentId: 0,
          permissionId: 5,
        },
      },
      paymentRecords: {
        module: 'paymentRecords',
        name: '付款记录',
        config: {
          path: '/paymentRecords',
          name: 'paymentRecords',
          fullPath: '/paymentRecords',
          title: '付款记录',
          icon: 'paymentRecords',
          activeIcon: 'paymentRecordsShine',
          component: import(/* webpackChunkName: "paymentRecords" */ '@/pages/paymentRecords/paymentRecords.vue'),
          children: [],
          default: '/paymentRecords',
          meta: { keepAlive: true, title: '付款记录' },
          projects: ['FK'],
          order: 6,
          parentId: 0,
          permissionId: 6,
        },
      },
      invoicePool: {
        module: 'invoicePool',
        name: '发票池',
        config: {
          path: '/invoicePool',
          name: 'invoicePool',
          fullPath: '/invoicePool',
          title: '发票池',
          icon: 'invoicePool',
          activeIcon: 'invoicePoolShine',
          component: import(/* webpackChunkName: "invoicePool" */ '@/pages/invoicePool/invoicePool.vue'),
          children: [],
          default: '/invoicePool',
          meta: { keepAlive: true, title: '发票池' },
          projects: ['FK'],
          order: 7,
          parentId: 0,
          permissionId: 7,
        },
      },
      expenseType: {
        module: 'expenseType',
        name: '费用类型',
        config: {
          path: '/expenseType',
          name: 'expenseType',
          fullPath: '/expenseType',
          title: '费用类型',
          icon: 'expenseType',
          activeIcon: 'expenseTypeShine',
          component: import(/* webpackChunkName: "expenseType" */ '@/pages/expenseType/expenseType.vue'),
          children: [],
          default: '/expenseType',
          meta: { keepAlive: true, title: '费用类型' },
          projects: ['FK'],
          order: 8,
          parentId: 0,
          permissionId: 8,
        },
      },
      companies: {
        module: 'companies',
        name: '公司档案',
        config: {
          path: '/companies',
          name: 'companies',
          fullPath: '/companies',
          title: '公司档案',
          icon: 'companies',
          activeIcon: 'companiesShine',
          component: import(/* webpackChunkName: "companies" */ '@/pages/companies/companies.vue'),
          children: [],
          default: '/companies',
          meta: { keepAlive: true, title: '公司档案' },
          projects: ['FK'],
          order: 9,
          parentId: 0,
          permissionId: 9,
        },
      },
      personnelFile: {
        module: 'personnelFile',
        name: '人员档案',
        config: {
          path: '/personnelFile',
          name: 'personnelFile',
          fullPath: '/personnelFile',
          title: '人员档案',
          icon: 'personnelFile',
          activeIcon: 'personnelFileShine',
          component: import(/* webpackChunkName: "personnelFile" */ '@/pages/personnelFile/personnelFile.vue'),
          children: [],
          default: '/personnelFile',
          meta: { keepAlive: true, title: '人员档案' },
          projects: ['FK'],
          order: 10,
          parentId: 0,
          permissionId: 10,
        },
      },
      paymentAccountManagement: {
        module: 'paymentAccountManagement',
        name: '支付账户管理',
        config: {
          path: '/paymentAccountManagement',
          name: 'paymentAccountManagement',
          fullPath: '/paymentAccountManagement',
          title: '支付账户管理',
          icon: 'paymentAccountManagement',
          activeIcon: 'paymentAccountManagementShine',
          component: import(/* webpackChunkName: "paymentAccountManagement" */ '@/pages/paymentAccountManagement/paymentAccountManagement.vue'),
          children: [],
          default: '/paymentAccountManagement',
          meta: { keepAlive: true, title: '支付账户管理' },
          projects: ['FK'],
          order: 11,
          parentId: 0,
          permissionId: 11,
        },
      },
      accountManagement: {
        module: 'accountManagement',
        name: '账户管理',
        config: {
          path: '/accountManagement',
          name: 'accountManagement',
          fullPath: '/accountManagement',
          title: '账户管理',
          icon: 'accountManagement',
          activeIcon: 'accountManagementShine',
          component: import(/* webpackChunkName: "accountManagement" */ '@/pages/accountManagement/accountManagement.vue'),
          children: [],
          default: '/accountManagement',
          meta: { keepAlive: true, title: '账户管理' },
          projects: ['FK'],
          order: 12,
          parentId: 0,
          permissionId: 12,
        },
      },
      voucherList: {
        module: 'voucherList',
        name: '凭证列表',
        config: {
          path: '/voucherList',
          name: 'voucherList',
          fullPath: '/voucherList',
          title: '凭证列表',
          icon: 'voucherList',
          activeIcon: 'voucherListShine',
          component: import(/* webpackChunkName: "voucherList" */ '@/pages/voucherList/voucherList.vue'),
          children: [],
          default: '/voucherList',
          meta: { keepAlive: true, title: '凭证列表' },
          projects: ['FK'],
          order: 13,
          parentId: 0,
          permissionId: 13,
        },
      },
      examineApprove: {
        module: 'examineApprove',
        name: '审批',
        config: {
          path: '/examineApprove',
          name: 'examineApprove',
          fullPath: '/examineApprove',
          title: '审批',
          icon: 'examineApprove',
          activeIcon: 'examineApproveShine',
          component: import(/* webpackChunkName: "examineApprove" */ '@/pages/examineApprove/examineApprove.vue'),
          children: [
            {
              path: '/examineApprove/expense',
              name: 'examineApproveExpense',
              fullPath: '/examineApprove/expense',
              title: '报销审批',
              icon: 'examineApproveExpense',
              activeIcon: 'examineApproveExpenseShine',
              component: import(/* webpackChunkName: "expense" */ '@/pages/examineApprove/views/expense.vue'),
              children: [],
              default: '/examineApprove/expense',
              meta: { keepAlive: true, title: '报销审批' },
              projects: ['FK'],
              order: 1,
              parentId: 14,
              permissionId: 14001,
            },
          ],
          default: '/examineApprove',
          meta: { keepAlive: true, title: '审批' },
          projects: ['FK'],
          order: 14,
          parentId: 0,
          permissionId: 14,
        },
      },
    };
    return data;
  }
}

export default new RouterData();
