export type AdminMenuRoute = {
  path: string;
  name: string;
  title: string;
  localeKey: string;
  icon: string;
  keepAlive?: boolean;
  component: () => Promise<unknown>;
};

export const adminMenuRoutes: AdminMenuRoute[] = [
  {
    path: '/dashboard',
    name: 'dashboard',
    title: '仪表盘',
    localeKey: 'menu.dashboard',
    icon: 'dashboard',
    keepAlive: true,
    component: () => import('@/pages/dashboard/dashboard.vue'),
  },
  {
    path: '/user-manage',
    name: 'userManage',
    title: '用户管理',
    localeKey: 'menu.userManage',
    icon: 'userManage',
    component: () => import('@/pages/userManage/userManage.vue'),
  },
  {
    path: '/home-manage',
    name: 'homeManage',
    title: '首页管理',
    localeKey: 'menu.homeManage',
    icon: 'homeManage',
    component: () => import('@/pages/homeManage/homeManage.vue'),
  },
  {
    path: '/search-operation-manage',
    name: 'searchOperationManage',
    title: '搜索运营',
    localeKey: 'menu.searchOperationManage',
    icon: 'searchOperationManage',
    component: () => import('@/pages/searchOperationManage/searchOperationManage.vue'),
  },
  {
    path: '/recommend-slot-manage',
    name: 'recommendSlotManage',
    title: '推荐位配置',
    localeKey: 'menu.recommendSlotManage',
    icon: 'recommendSlotManage',
    component: () => import('@/pages/recommendSlotManage/recommendSlotManage.vue'),
  },
  {
    path: '/course-manage',
    name: 'courseManage',
    title: '课程管理',
    localeKey: 'menu.courseManage',
    icon: 'courseManage',
    component: () => import('@/pages/courseManage/courseManage.vue'),
  },
  {
    path: '/garden-manage',
    name: 'gardenManage',
    title: '园地管理',
    localeKey: 'menu.gardenManage',
    icon: 'gardenManage',
    component: () => import('@/pages/gardenManage/gardenManage.vue'),
  },
  {
    path: '/member-manage',
    name: 'memberManage',
    title: '会员管理',
    localeKey: 'menu.memberManage',
    icon: 'memberManage',
    component: () => import('@/pages/memberManage/memberManage.vue'),
  },
  {
    path: '/member-package-manage',
    name: 'memberPackageManage',
    title: '会员套餐',
    localeKey: 'menu.memberPackageManage',
    icon: 'memberPackageManage',
    component: () => import('@/pages/memberPackageManage/memberPackageManage.vue'),
  },
  {
    path: '/growth-rule-manage',
    name: 'growthRuleManage',
    title: '成长规则',
    localeKey: 'menu.growthRuleManage',
    icon: 'growthRuleManage',
    component: () => import('@/pages/growthRuleManage/growthRuleManage.vue'),
  },
  {
    path: '/message-manage',
    name: 'messageManage',
    title: '消息管理',
    localeKey: 'menu.messageManage',
    icon: 'messageManage',
    component: () => import('@/pages/messageManage/messageManage.vue'),
  },
  {
    path: '/message-template-manage',
    name: 'messageTemplateManage',
    title: '消息模板',
    localeKey: 'menu.messageTemplateManage',
    icon: 'messageTemplateManage',
    component: () => import('@/pages/messageTemplateManage/messageTemplateManage.vue'),
  },
  {
    path: '/service-manage',
    name: 'serviceManage',
    title: '客服管理',
    localeKey: 'menu.serviceManage',
    icon: 'serviceManage',
    component: () => import('@/pages/serviceManage/serviceManage.vue'),
  },
  {
    path: '/system-manage',
    name: 'systemManage',
    title: '系统管理',
    localeKey: 'menu.systemManage',
    icon: 'systemManage',
    component: () => import('@/pages/systemManage/systemManage.vue'),
  },
  {
    path: '/report-audit',
    name: 'reportAudit',
    title: '举报审核',
    localeKey: 'menu.reportAudit',
    icon: 'reportAudit',
    component: () => import('@/pages/reportAudit/reportAudit.vue'),
  },
  {
    path: '/sensitive-word-manage',
    name: 'sensitiveWordManage',
    title: '敏感词管理',
    localeKey: 'menu.sensitiveWordManage',
    icon: 'sensitiveWordManage',
    component: () => import('@/pages/sensitiveWordManage/sensitiveWordManage.vue'),
  },
  {
    path: '/question-bank-manage',
    name: 'questionBankManage',
    title: '题库管理',
    localeKey: 'menu.questionBankManage',
    icon: 'questionBankManage',
    component: () => import('@/pages/questionBankManage/questionBankManage.vue'),
  },
  {
    path: '/practice-paper-manage',
    name: 'practicePaperManage',
    title: '练习试卷',
    localeKey: 'menu.practicePaperManage',
    icon: 'practicePaperManage',
    component: () => import('@/pages/practicePaperManage/practicePaperManage.vue'),
  },
  {
    path: '/statistics',
    name: 'statistics',
    title: '数据统计',
    localeKey: 'menu.statistics',
    icon: 'statistics',
    component: () => import('@/pages/statistics/statistics.vue'),
  },
  {
    path: '/logs',
    name: 'logs',
    title: '日志管理',
    localeKey: 'menu.logs',
    icon: 'logs',
    component: () => import('@/pages/logs/logs.vue'),
  },
];
